# ----------------------------------------------------------------------------
# Name:         salt/pillars/linux/certificates.sls
# Description:  Salt pillar file for linux certificate trust configuration
# Author:       Michael Poore (@mpoore / @mpoore.io)
# URL:          https://github.com/mpoore/packer
# ----------------------------------------------------------------------------
trustedcertificates:
  mpoore-root: |
    -----BEGIN CERTIFICATE-----
    MIIFdzCCA1+gAwIBAgIULrQ8f5P6yguNkB5m0TNWXG4A6UUwDQYJKoZIhvcNAQEL
    BQAwQzELMAkGA1UEBhMCR0IxFTATBgNVBAoTDG1wb29yZS5jbG91ZDEdMBsGA1UE
    AxMUbXBvb3JlLmNsb3VkIFJvb3QgQ0EwHhcNMjYwNjA4MTA1MTU3WhcNNDEwNjA0
    MTA1MjI2WjBDMQswCQYDVQQGEwJHQjEVMBMGA1UEChMMbXBvb3JlLmNsb3VkMR0w
    GwYDVQQDExRtcG9vcmUuY2xvdWQgUm9vdCBDQTCCAiIwDQYJKoZIhvcNAQEBBQAD
    ggIPADCCAgoCggIBAPQYJMKpDqTdggurayzZfXkWEZjDWcNjImmV2Bjbl30eVqjM
    fOLgisJeKmAsgCazVce+N4MVtd8kP8SfJZhYj7SgtSsRfFOp3TS2DsCrsunYpvzP
    BNSHZSXYO2fyRskaOaT/K5jzvmiyEvar4eHHn1JwDYVJWuppx9s1deeHQqzpGgCt
    Syu0ApKcjd+a9Lz+ZY0/ljbeLAsq9pSxY/tlGr92s/OdGgmLb0yFl0iQKdNbxtNK
    KHPoLLSD9JG5P4yLeCK9ucgp6ySlYhinuuRPR7A5suCwLKIPGpb2NkPYPXbyhBv3
    AGBOcxYvSxSFO4eBvyjMtsCZ+uTBy0dZ8Vu2tFu1rcMtj5lyqKrRuKyX+Bd5+J7C
    nprmnGMSncnDZT/ZRyFUYX+1Jqwh52+U3QBJIHeI4RZkm19ZzKUKKKHf8lfIjegc
    Iz6MP8CDNMDkQanV1oq3QWNxoADPBa6fcZw9Fa0nXXtX0+pExgvpZipW/9rDidyr
    G/e2Atfhp+QRPhLaf+crc11YmMAuU6OnOpO9FBRAySAvnZqydp8nFb8/Xx11IRb3
    S7ybrlnVekrd7Zg1LXm/xnLr8Y6fLM7fnmzQMB9/G8WTLubzxjXhCB0ulrfh2EK4
    8WuziIjD4+VcRwV7zHjdPzhc4O6fx+lR10bRnJmd2sJSY50CpV3sNNlHwN4pAgMB
    AAGjYzBhMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
    BBQ1kc8Lo7ddfJGZgKUamuKy080CfzAfBgNVHSMEGDAWgBQ1kc8Lo7ddfJGZgKUa
    muKy080CfzANBgkqhkiG9w0BAQsFAAOCAgEA4TGMhPJoE0h0MJs9ngDm2sqcDD/Z
    pYREPT18fXcm0/JCCWq28GeQ20UYNMELTwS1dhrwhQFJW+o56cex1p07FBfRbjJE
    7/i+ZhlrmbyIx0EuBZwm+gZQ3GgO431kb8GGZ/vaHwTpMkArOJnbzsZNDtqT2KMP
    YvJoiYRP+tm1b3BBhpfDViCmz7MtzFt+jGQVNwWa6hvzBxNS5XX2p9h16pTZRLXA
    ZQcTJGGpV/UG9Htpr/9Ic48j6I5sfT5rAYZ2YoklNqsEq3sdtb0BRvngyaGdyJEB
    M8DWVUWc7A2AElB5TsIWQn7ZesK0Ug72kX9GJj9n5QzGNRUFNzFO2f3gH7EGZr7u
    GqZwQyXkb6A1z1q8OpQkgbyZklhFPsIZHP9uQdqCUJ7JXAWvRmH8NkeueXoFzG4p
    /QPIMrrHfeMbpqvZAcalF9SAdTizfJY8fFMvIAOIXa365UcgDUfjiy+oHrKdPSRO
    mdpZ8Vkh3uCD+jqCqoMECRsFN2pV63FRhIuxLyaHmrtunIswSdeaC8+tctIL9hIH
    hZUvscwuspyLOLDe+GOoY9O05TqjgWZqFSTpDh0N54VdejkprLQQz1HiPrtw7KdC
    5I6debgPV0EbjK4Lm/QUl+KqjHLN0zBLPpaZAUUOgorAlF7k3gmzG/3ZvnoDLZjp
    +Xq+IdVNbSynmDk=
    -----END CERTIFICATE-----
  mpoore-issuing: |
    -----BEGIN CERTIFICATE-----
    MIIGSDCCBDCgAwIBAgIUYGSaDpyVlt97oVcaqDdrtSFNp2MwDQYJKoZIhvcNAQEL
    BQAwQzELMAkGA1UEBhMCR0IxFTATBgNVBAoTDG1wb29yZS5jbG91ZDEdMBsGA1UE
    AxMUbXBvb3JlLmNsb3VkIFJvb3QgQ0EwHhcNMjYwNjA4MTEyNDQ2WhcNMzEwNjA3
    MTEyNTE2WjBGMQswCQYDVQQGEwJHQjEVMBMGA1UEChMMbXBvb3JlLmNsb3VkMSAw
    HgYDVQQDExdtcG9vcmUuY2xvdWQgSXNzdWluZyBDQTCCAiIwDQYJKoZIhvcNAQEB
    BQADggIPADCCAgoCggIBAKhy3guDSUDYSlNMyLnuUt4pm3RFiDB6YnBQPNXEZ9CD
    bpy7Fda2GJk2P9Z8jZK+TtJOt2tcQeM/lIkzIM3QeAGH4TNC9iMc7ZBIMvrwVMO1
    h32lT6qL6w+3YezrUHEw6eYrN/bxxJEhhn9MN/4cay0UkJRLHxetexYiEiO3lNrv
    tJaZ+BYU55loNvLnSjzQn1s8ckEY6ySpvtaGaqJgDG/2cZ/UCGN/Uj+MgsVdMnzT
    UhtdVoCzI18wrZJngOnUE2XzUMXS+72q/gVIBaQPJ7bXw6QkZkyaZTsdCwQIxCXZ
    1Nl+Cgan0qQ2Jh6ezo4vXEDTkCxJMpSPftGM0HEZklcb64U7A2UnqiXNFIsx7xyb
    D6G7E36Jy7oVtnKwT0END1IyD807ODEi0mW/McUc3wodplx9Ste6dgt1yx9TaoAw
    zquLaSET1y0UYS/ObMeDzvDDvCX+CmMqdoFpTZgB2zgh2jrNMopWg/BhheBEMDCx
    UTX+wod0ouufmsIey+BolhaKoriOdTmi9nYZT426drdJmaptXjwBNf9W+CtjN9TK
    70wJtUpOoMrlggT/9echKCsH1AN/3MVoLWtmCeBep7SyCthdin/2rFs5++BHOWav
    vksMw7cpHtmZTfXUQOWe/HumnH/+uY8H1++dMpXki6LR9ojcTq+1pBlckwOjfQEN
    AgMBAAGjggEvMIIBKzAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAd
    BgNVHQ4EFgQURp27sYuXxA1mwn+P4yxppi85k1swHwYDVR0jBBgwFoAUNZHPC6O3
    XXyRmYClGpristPNAn8wgYYGCCsGAQUFBwEBBHoweDA7BggrBgEFBQcwAYYvaHR0
    cDovL3ZhdWx0Lm1wb29yZS5jbG91ZDo4MjAwL3YxL3BraS1yb290L29jc3AwOQYI
    KwYBBQUHMAKGLWh0dHA6Ly92YXVsdC5tcG9vcmUuY2xvdWQ6ODIwMC92MS9wa2kt
    cm9vdC9jYTA/BgNVHR8EODA2MDSgMqAwhi5odHRwOi8vdmF1bHQubXBvb3JlLmNs
    b3VkOjgyMDAvdjEvcGtpLXJvb3QvY3JsMA0GCSqGSIb3DQEBCwUAA4ICAQBLT2sG
    aaEPReGL1d2PKocr/Trus4q6EXQ+VTtk9edpjRYtTy1kmVCdbKiWFbmCXP3kQD6u
    f2nwS6yAEzLtx5f/7CkYxYnJZcLV8dcrfdyeNlIS5aHz5bpXOEMFFBex/Z8no1tU
    K3FCqDnynUkdngF3d91Oif6c62kYN1+70LNLAe4j16txwLTV0AugaCd9/Eta0L6r
    Dp1L2BJ+CBKvgV6Q4waz1z8iF59BE1NFoJTdS4fUITWbamcW+KpE+TPhqvmIKS8q
    tHRGSTj9C7kCzunDwEgAmbVileIUdVyjxsRH19bI/RA705tXq0ll3WfOJR5guaVy
    EFGldm4CALVMGnuJGm6B23oXjsCUIni5tmEUF+AGeqqfT/6jhZ2NYyLD8yHIq5bv
    p265EmRs22u5PHtTLSn+TmZYZTKfRG2cVRS8sJOws9NrrHu6AGDuC7iBLzI3Lx+8
    nZ7lCFuhMV/mfrwygbCbDxkQgvih3mBxO0fyHWv1Ea7/a5vKmFoP5p0RFwe2xpDz
    oZCbvZavSdfGnlj9QLfbMYSerSh0VjYFvJtAaYY1eO1h2eO+yqwMq3CsuJG7TPbx
    lTz6CcH5Hn+kNw6GYUKj5rJQnPiJ0fFzkuC2YB8zIg8nL/+Pfec1unlZeEojoQxF
    Ekscg3OSUOYCaRfwzsalAxw7a70P8CHP4lJ/wQ==
    -----END CERTIFICATE-----
  isrg-root-x2: |
    -----BEGIN CERTIFICATE-----
    MIICGzCCAaGgAwIBAgIQQdKd0XLq7qeAwSxs6S+HUjAKBggqhkjOPQQDAzBPMQsw
    CQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFyY2gg
    R3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMjAeFw0yMDA5MDQwMDAwMDBaFw00
    MDA5MTcxNjAwMDBaME8xCzAJBgNVBAYTAlVTMSkwJwYDVQQKEyBJbnRlcm5ldCBT
    ZWN1cml0eSBSZXNlYXJjaCBHcm91cDEVMBMGA1UEAxMMSVNSRyBSb290IFgyMHYw
    EAYHKoZIzj0CAQYFK4EEACIDYgAEzZvVn4CDCuwJSvMWSj5cz3es3mcFDR0HttwW
    +1qLFNvicWDEukWVEYmO6gbf9yoWHKS5xcUy4APgHoIYOIvXRdgKam7mAHf7AlF9
    ItgKbppbd9/w+kHsOdx1ymgHDB/qo0IwQDAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0T
    AQH/BAUwAwEB/zAdBgNVHQ4EFgQUfEKWrt5LSDv6kviejM9ti6lyN5UwCgYIKoZI
    zj0EAwMDaAAwZQIwe3lORlCEwkSHRhtFcP9Ymd70/aTSVaYgLXTWNLxBo1BfASdW
    tL4ndQavEi51mI38AjEAi/V3bNTIZargCyzuFJ0nN6T5U6VR5CmD1/iQMVtCnwr1
    /q4AaOeMSQ+2b1tbFfLn
    -----END CERTIFICATE-----
  isrg-e5: |
    -----BEGIN CERTIFICATE-----
    MIICtDCCAjugAwIBAgIQGG511O6woF39Lagghl0eMTAKBggqhkjOPQQDAzBPMQsw
    CQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFyY2gg
    R3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMjAeFw0yNDAzMTMwMDAwMDBaFw0y
    NzAzMTIyMzU5NTlaMDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNy
    eXB0MQswCQYDVQQDEwJFNTB2MBAGByqGSM49AgEGBSuBBAAiA2IABA0LOoprYY62
    79xfWOfGQkVUq2P2ZmFICi5ZdbSBAjdQtz8WedyY7KEol3IgHCzP1XxSIE5UeFuE
    FGvAkK6F7MBRQTxah38GTdT+YNH6bC3hfZUQiKIIVA+ZGkzm6gqs2KOB+DCB9TAO
    BgNVHQ8BAf8EBAMCAYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIG
    A1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFJ8rX888IU+dBLftKyzExnCL0tcN
    MB8GA1UdIwQYMBaAFHxClq7eS0g7+pL4nozPbYupcjeVMDIGCCsGAQUFBwEBBCYw
    JDAiBggrBgEFBQcwAoYWaHR0cDovL3gyLmkubGVuY3Iub3JnLzATBgNVHSAEDDAK
    MAgGBmeBDAECATAnBgNVHR8EIDAeMBygGqAYhhZodHRwOi8veDIuYy5sZW5jci5v
    cmcvMAoGCCqGSM49BAMDA2cAMGQCMBttLkVBHEU+2V80GHRnE3m6qym1thBOgydK
    i0VOx3vP9EAwHWGl5hxtpJAJkm5GSwIwRikYhDR6vPve2BvYGacE9ct+522E2dqO
    6s42MLmigEws5mASS6l2quhtlUfacgkM
    -----END CERTIFICATE-----
  isrg-e6: |
    -----BEGIN CERTIFICATE-----
    MIICtjCCAjygAwIBAgIRAICpc0jvJ2ip4/a7Q8D5xikwCgYIKoZIzj0EAwMwTzEL
    MAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2VhcmNo
    IEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDIwHhcNMjQwMzEzMDAwMDAwWhcN
    MjcwMzEyMjM1OTU5WjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3MgRW5j
    cnlwdDELMAkGA1UEAxMCRTYwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAATZ8Z5Gh/gh
    cWCoJuuj+rnq2h25EqfUJtlRFLFhfHWWvyILOR/VvtEKRqotPEoJhC6+QJVV6RlA
    N2Z17TJOdwRJ+HB7wxjnzvdxEP6sdNgA1O1tHHMWMxCcOrLqbGL0vbijgfgwgfUw
    DgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAS
    BgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBSTJ0aYA6lRaI6Y1sRCSNsjv1iU
    0jAfBgNVHSMEGDAWgBR8Qpau3ktIO/qS+J6Mz22LqXI3lTAyBggrBgEFBQcBAQQm
    MCQwIgYIKwYBBQUHMAKGFmh0dHA6Ly94Mi5pLmxlbmNyLm9yZy8wEwYDVR0gBAww
    CjAIBgZngQwBAgEwJwYDVR0fBCAwHjAcoBqgGIYWaHR0cDovL3gyLmMubGVuY3Iu
    b3JnLzAKBggqhkjOPQQDAwNoADBlAjBgGMvAszhCd1BsRuMwGYCC0QCzf5d//MC5
    ASqIyswj3hGcoZREOKDKdvJPHhgdZr8CMQCWq4Kjl/RmuF49LBq9eP7oGWAc55w4
    G72FoKw5a9WywSwBzoJunrayTB8nDSjEhu8=
    -----END CERTIFICATE-----