# ----------------------------------------------------------------------------
# Name:         salt/pillars/linux/certificates.sls
# Description:  Salt pillar file for linux certificate trust configuration
# Author:       Michael Poore (@mpoore / @mpoore.io)
# URL:          https://github.com/mpoore/packer
# ----------------------------------------------------------------------------
trustedcertificates:
  mpoore-root: |
    -----BEGIN CERTIFICATE-----
    MIIDKzCCAhOgAwIBAgIUMN4KWDbyudypEYlytVMnY4Y7yGUwDQYJKoZIhvcNAQEL
    BQAwHTEbMBkGA1UEAxMSbGFiLm1wb29yZS5pbyBSb290MB4XDTI1MDMxNTEzNDU0
    OFoXDTQ1MDMxMDEzNDYxOFowHTEbMBkGA1UEAxMSbGFiLm1wb29yZS5pbyBSb290
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw/s3bMEFh8rACoZBUDZi
    pClTLqZ9VN3pG/PdXDtl7YArd6iUO/kvuMmT92y3KnKU4ncoiESrSDcYmy4jIcwm
    3V/LB6uy4Wgzbo/7R+f+oBjwMkebIe3nOW0/1RJCA9CTCVpCFLJN976SzKepKhRB
    lEeJ0eIq1+Nc6+Sp0mMW/nXkIF8BUt3tCGrEKcDXZtFDQ7o+p7XR7yhIJbGkowT3
    ouU7iCxlxEfCZ2rI874c38ueyD6fIm8/poLq9LMWY2Jqs5fWffHTFK5TgIzk88Vb
    wB1IP3VAFj7+Et7VerPkzOqOu3jEFxhiDJcijs5C68HqBUrC7DhJNqJsFz012Cbu
    dQIDAQABo2MwYTAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNV
    HQ4EFgQUtjMw9wel4g9Vw/PqUS1gnF99S4owHwYDVR0jBBgwFoAUtjMw9wel4g9V
    w/PqUS1gnF99S4owDQYJKoZIhvcNAQELBQADggEBAHtCp10P4VZTrhvcAZXlCnIK
    zyrDvK5HqpGhhcCikNLaj52RktHgYoH9Hxje23oR2+/yskGBliE/tpg3Rb4o6x1A
    TGF/XG+923fi2ONwp1T++FlDEOlWjYlQ2AVB94JQAop/A5rRbyhW2W4p5xLeggQg
    kbRM5d1lcyjEE9a3zMMJ8UJAbvcK5PJGw1w9YPI2t02vtfo7Kljy3/QDHA/OhU8V
    K0H+LYDvn+0GPojcnkYBED1J7CGaFWIqqi1GBsdO4BIYKm90EO7Z2p8CfkwjgoOo
    3GutcN/rnxEwwtcG/CNqxFmKDlonsdgFDfHJIKISo3sr/2jJgpp/9sIotCphbWM=
    -----END CERTIFICATE-----
  mpoore-int: |
    -----BEGIN CERTIFICATE-----
    MIIDwzCCAqugAwIBAgIUYriLDQDGboD7KRV+GjjW+9Nf2gMwDQYJKoZIhvcNAQEL
    BQAwHTEbMBkGA1UEAxMSbGFiLm1wb29yZS5pbyBSb290MB4XDTI1MDMxNTEzNTQz
    MVoXDTMwMDMxNDEzNTUwMVowLzEtMCsGA1UEAxMkbGFiLm1wb29yZS5pbyBJbnRl
    cm1lZGlhdGUgQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
    AQEAthqr6fQv/LO73isLNIy83KN12/eUgbCWfUj78RlMHRuWI9u4wKSDZ24zBTj7
    04XI2M6mXyQ4BA+xYxxXFsG/cNEFq5zPanJl0i0cSAPpz+OGVpLTBYSwBJW3Hg8W
    pyQNamDmwDVey/EdqrdhfKSRA4OBv53I956H518oZhUvYPb1CJQOWoJEkTXaOgc4
    13VXidX74THW5kAVoS0rLqi7D56zZzRAN5zlX31vP36ubRQc/T5IEaa592U7RFBn
    ajkVFDZ1jU4U1S1Jj60oMQyujQg2ObRwZ+TF5KcujkNtiBtVPIcInz3x2w6lz2x4
    peJK67rLbcP7CGx6RW59maVoJwIDAQABo4HoMIHlMA4GA1UdDwEB/wQEAwIBBjAP
    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTxECA6DrB1DY1gP4PJM8MPUESpRjAf
    BgNVHSMEGDAWgBS2MzD3B6XiD1XD8+pRLWCcX31LijBFBggrBgEFBQcBAQQ5MDcw
    NQYIKwYBBQUHMAKGKWh0dHA6Ly92YXVsdC5sYWIubXBvb3JlLmlvOjgyMDAvdjEv
    cGtpL2NhMDsGA1UdHwQ0MDIwMKAuoCyGKmh0dHA6Ly92YXVsdC5sYWIubXBvb3Jl
    LmlvOjgyMDAvdjEvcGtpL2NybDANBgkqhkiG9w0BAQsFAAOCAQEApaXcUEUqCV5A
    khPNEORQGWuB1WpnCMLhUYume9szgS2rT6DxYSIPj2zGwSP4dwFMXcpxoLuYtTNQ
    xVelfHveOdEIRElWsRyJsbKIwATJE7jHBwCfewd2mof5PH7KkogSLBBT6CQBTkBl
    C6XDUf5qUwI3rHswqsQIkLuRxYWzsdSb/Xz894yCbiefnm+6M1KqL0y3L9SlSdlh
    2fIyGCjHFmw+BVcteqgAVlglQ0PabvVWz+diV6hWTk2XE91r+18ZcqNYDrHMzqC4
    0ceUTp33euehr3ks6nngG2usSXVtzzdHWruhT8jByIyMWtVQ3KhZ708hY8/UGbj5
    +2b5XesYKw==
    -----END CERTIFICATE-----
  isrg-root-x2: |
    -----BEGIN CERTIFICATE-----
    MIICGzCCAaGgAwIBAgIQQdKd0XLq7qeAwSxs6S+HUjAKBggqhkjOPQQDAzBPMQsw
    CQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFyY2gg
    R3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMjAeFw0yMDA5MDQwMDAwMDBaFw00
    MDA5MTcxNjAwMDBaME8xCzAJBgNVBAYTAlVTMSkwJwYDVQQKEyBJbnRlcm5ldCBT
    ZWN1cml0eSBSZXNlYXJjaCBHcm91cDEVMBMGA1UEAxMMSVNSRyBSb290IFgyMHYw
    EAYHKoZIzj0CAQYFK4EEACIDYgAEzZvVn4CDCuwJSvMWSj5cz3es3mcFDR0HttwW
    +1qLFNvicWDEukWVEYmO6gbf9yoWHKS5xcUy4APgHoIYOIvXRdgKam7mAHf7AlF9
    ItgKbppbd9/w+kHsOdx1ymgHDB/qo0IwQDAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0T
    AQH/BAUwAwEB/zAdBgNVHQ4EFgQUfEKWrt5LSDv6kviejM9ti6lyN5UwCgYIKoZI
    zj0EAwMDaAAwZQIwe3lORlCEwkSHRhtFcP9Ymd70/aTSVaYgLXTWNLxBo1BfASdW
    tL4ndQavEi51mI38AjEAi/V3bNTIZargCyzuFJ0nN6T5U6VR5CmD1/iQMVtCnwr1
    /q4AaOeMSQ+2b1tbFfLn
    -----END CERTIFICATE-----
  isrg-e5: |
    -----BEGIN CERTIFICATE-----
    MIICtDCCAjugAwIBAgIQGG511O6woF39Lagghl0eMTAKBggqhkjOPQQDAzBPMQsw
    CQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFyY2gg
    R3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMjAeFw0yNDAzMTMwMDAwMDBaFw0y
    NzAzMTIyMzU5NTlaMDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNy
    eXB0MQswCQYDVQQDEwJFNTB2MBAGByqGSM49AgEGBSuBBAAiA2IABA0LOoprYY62
    79xfWOfGQkVUq2P2ZmFICi5ZdbSBAjdQtz8WedyY7KEol3IgHCzP1XxSIE5UeFuE
    FGvAkK6F7MBRQTxah38GTdT+YNH6bC3hfZUQiKIIVA+ZGkzm6gqs2KOB+DCB9TAO
    BgNVHQ8BAf8EBAMCAYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIG
    A1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFJ8rX888IU+dBLftKyzExnCL0tcN
    MB8GA1UdIwQYMBaAFHxClq7eS0g7+pL4nozPbYupcjeVMDIGCCsGAQUFBwEBBCYw
    JDAiBggrBgEFBQcwAoYWaHR0cDovL3gyLmkubGVuY3Iub3JnLzATBgNVHSAEDDAK
    MAgGBmeBDAECATAnBgNVHR8EIDAeMBygGqAYhhZodHRwOi8veDIuYy5sZW5jci5v
    cmcvMAoGCCqGSM49BAMDA2cAMGQCMBttLkVBHEU+2V80GHRnE3m6qym1thBOgydK
    i0VOx3vP9EAwHWGl5hxtpJAJkm5GSwIwRikYhDR6vPve2BvYGacE9ct+522E2dqO
    6s42MLmigEws5mASS6l2quhtlUfacgkM
    -----END CERTIFICATE-----
  isrg-e6: |
    -----BEGIN CERTIFICATE-----
    MIICtjCCAjygAwIBAgIRAICpc0jvJ2ip4/a7Q8D5xikwCgYIKoZIzj0EAwMwTzEL
    MAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2VhcmNo
    IEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDIwHhcNMjQwMzEzMDAwMDAwWhcN
    MjcwMzEyMjM1OTU5WjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3MgRW5j
    cnlwdDELMAkGA1UEAxMCRTYwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAATZ8Z5Gh/gh
    cWCoJuuj+rnq2h25EqfUJtlRFLFhfHWWvyILOR/VvtEKRqotPEoJhC6+QJVV6RlA
    N2Z17TJOdwRJ+HB7wxjnzvdxEP6sdNgA1O1tHHMWMxCcOrLqbGL0vbijgfgwgfUw
    DgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAS
    BgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBSTJ0aYA6lRaI6Y1sRCSNsjv1iU
    0jAfBgNVHSMEGDAWgBR8Qpau3ktIO/qS+J6Mz22LqXI3lTAyBggrBgEFBQcBAQQm
    MCQwIgYIKwYBBQUHMAKGFmh0dHA6Ly94Mi5pLmxlbmNyLm9yZy8wEwYDVR0gBAww
    CjAIBgZngQwBAgEwJwYDVR0fBCAwHjAcoBqgGIYWaHR0cDovL3gyLmMubGVuY3Iu
    b3JnLzAKBggqhkjOPQQDAwNoADBlAjBgGMvAszhCd1BsRuMwGYCC0QCzf5d//MC5
    ASqIyswj3hGcoZREOKDKdvJPHhgdZr8CMQCWq4Kjl/RmuF49LBq9eP7oGWAc55w4
    G72FoKw5a9WywSwBzoJunrayTB8nDSjEhu8=
    -----END CERTIFICATE-----